spring:
  cloud:
    consul:
      host: 192.168.2.80
      port: 8500
      discovery:
        health-check-path: /health
        health-check-interval: 15s
        instance-id: consul-miya
  application:
    name: consul-miya
server:
  port: 8502
